package com.csjscm.core.framework.dao;

import com.csjscm.core.framework.model.SkuCore;

public interface SkuCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_core
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int deleteByPrimaryKey(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_core
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int insert(SkuCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_core
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int insertSelective(SkuCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_core
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    SkuCore selectByPrimaryKey(String productNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_core
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int updateByPrimaryKeySelective(SkuCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_core
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int updateByPrimaryKey(SkuCore record);
}