package com.csjscm.core.framework.dao;

import com.csjscm.core.framework.model.SkuPartner;

public interface SkuPartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_partner
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_partner
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int insert(SkuPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_partner
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int insertSelective(SkuPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_partner
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    SkuPartner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_partner
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int updateByPrimaryKeySelective(SkuPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_partner
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int updateByPrimaryKey(SkuPartner record);
}