package com.csjscm.core.framework.dao;

import com.csjscm.core.framework.model.SkuSell;

public interface SkuSellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int insert(SkuSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int insertSelective(SkuSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    SkuSell selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int updateByPrimaryKeySelective(SkuSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Fri Aug 31 11:50:34 CST 2018
     */
    int updateByPrimaryKey(SkuSell record);
}