package com.csjscm.core.framework.dao;

import com.csjscm.core.framework.model.SkuSell;
import com.csjscm.core.framework.model.SkuSellExample;
import java.util.List;

import com.csjscm.core.framework.model.SkuSell;
import com.csjscm.core.framework.model.SkuSellExample;
import org.apache.ibatis.annotations.Param;

public interface SkuSellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int countByExample(SkuSellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int deleteByExample(SkuSellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int insert(SkuSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int insertSelective(SkuSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    List<SkuSell> selectByExample(SkuSellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    SkuSell selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") SkuSell record, @Param("example") SkuSellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByExample(@Param("record") SkuSell record, @Param("example") SkuSellExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByPrimaryKeySelective(SkuSell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_sell
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByPrimaryKey(SkuSell record);
}