package cn.evun.coreframework.model;

public class BrandMasterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.brand_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.id
     *
     * @return the value of brand_master.id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.id
     *
     * @param id the value for brand_master.id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.brand_id
     *
     * @return the value of brand_master.brand_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.brand_id
     *
     * @param brandId the value for brand_master.brand_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }
}