package cn.evun.coreframework.model;

import java.util.Date;

public class BrandMaster extends BrandMasterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.brand_name
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.brand_pic
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String brandPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.brand_info
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String brandInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.brand_ca
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String brandCa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_master.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Date editTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.brand_name
     *
     * @return the value of brand_master.brand_name
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.brand_name
     *
     * @param brandName the value for brand_master.brand_name
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.brand_pic
     *
     * @return the value of brand_master.brand_pic
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getBrandPic() {
        return brandPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.brand_pic
     *
     * @param brandPic the value for brand_master.brand_pic
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setBrandPic(String brandPic) {
        this.brandPic = brandPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.brand_info
     *
     * @return the value of brand_master.brand_info
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getBrandInfo() {
        return brandInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.brand_info
     *
     * @param brandInfo the value for brand_master.brand_info
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setBrandInfo(String brandInfo) {
        this.brandInfo = brandInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.brand_ca
     *
     * @return the value of brand_master.brand_ca
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getBrandCa() {
        return brandCa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.brand_ca
     *
     * @param brandCa the value for brand_master.brand_ca
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setBrandCa(String brandCa) {
        this.brandCa = brandCa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.create_user_id
     *
     * @return the value of brand_master.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.create_user_id
     *
     * @param createUserId the value for brand_master.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.create_time
     *
     * @return the value of brand_master.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.create_time
     *
     * @param createTime the value for brand_master.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.edit_user_id
     *
     * @return the value of brand_master.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.edit_user_id
     *
     * @param editUserId the value for brand_master.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_master.edit_time
     *
     * @return the value of brand_master.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_master.edit_time
     *
     * @param editTime the value for brand_master.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }
}