package cn.evun.coreframework.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkuCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public SkuCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNull() {
            addCriterion("product_no is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("product_no is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("product_no =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("product_no <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("product_no >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("product_no >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("product_no <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("product_no <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("product_no like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("product_no not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("product_no in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("product_no not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("product_no between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("product_no not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(String value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(String value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(String value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(String value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLike(String value) {
            addCriterion("customer_id like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotLike(String value) {
            addCriterion("customer_id not like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<String> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<String> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(String value1, String value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(String value1, String value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIsNull() {
            addCriterion("customer_no is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIsNotNull() {
            addCriterion("customer_no is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNoEqualTo(String value) {
            addCriterion("customer_no =", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotEqualTo(String value) {
            addCriterion("customer_no <>", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoGreaterThan(String value) {
            addCriterion("customer_no >", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoGreaterThanOrEqualTo(String value) {
            addCriterion("customer_no >=", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLessThan(String value) {
            addCriterion("customer_no <", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLessThanOrEqualTo(String value) {
            addCriterion("customer_no <=", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoLike(String value) {
            addCriterion("customer_no like", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotLike(String value) {
            addCriterion("customer_no not like", value, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoIn(List<String> values) {
            addCriterion("customer_no in", values, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotIn(List<String> values) {
            addCriterion("customer_no not in", values, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoBetween(String value1, String value2) {
            addCriterion("customer_no between", value1, value2, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerNoNotBetween(String value1, String value2) {
            addCriterion("customer_no not between", value1, value2, "customerNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoIsNull() {
            addCriterion("customer_pd_no is null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoIsNotNull() {
            addCriterion("customer_pd_no is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoEqualTo(String value) {
            addCriterion("customer_pd_no =", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoNotEqualTo(String value) {
            addCriterion("customer_pd_no <>", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoGreaterThan(String value) {
            addCriterion("customer_pd_no >", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoGreaterThanOrEqualTo(String value) {
            addCriterion("customer_pd_no >=", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoLessThan(String value) {
            addCriterion("customer_pd_no <", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoLessThanOrEqualTo(String value) {
            addCriterion("customer_pd_no <=", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoLike(String value) {
            addCriterion("customer_pd_no like", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoNotLike(String value) {
            addCriterion("customer_pd_no not like", value, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoIn(List<String> values) {
            addCriterion("customer_pd_no in", values, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoNotIn(List<String> values) {
            addCriterion("customer_pd_no not in", values, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoBetween(String value1, String value2) {
            addCriterion("customer_pd_no between", value1, value2, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNoNotBetween(String value1, String value2) {
            addCriterion("customer_pd_no not between", value1, value2, "customerPdNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameIsNull() {
            addCriterion("customer_pd_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameIsNotNull() {
            addCriterion("customer_pd_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameEqualTo(String value) {
            addCriterion("customer_pd_name =", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameNotEqualTo(String value) {
            addCriterion("customer_pd_name <>", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameGreaterThan(String value) {
            addCriterion("customer_pd_name >", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_pd_name >=", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameLessThan(String value) {
            addCriterion("customer_pd_name <", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameLessThanOrEqualTo(String value) {
            addCriterion("customer_pd_name <=", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameLike(String value) {
            addCriterion("customer_pd_name like", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameNotLike(String value) {
            addCriterion("customer_pd_name not like", value, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameIn(List<String> values) {
            addCriterion("customer_pd_name in", values, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameNotIn(List<String> values) {
            addCriterion("customer_pd_name not in", values, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameBetween(String value1, String value2) {
            addCriterion("customer_pd_name between", value1, value2, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdNameNotBetween(String value1, String value2) {
            addCriterion("customer_pd_name not between", value1, value2, "customerPdName");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleIsNull() {
            addCriterion("customer_pd_rule is null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleIsNotNull() {
            addCriterion("customer_pd_rule is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleEqualTo(String value) {
            addCriterion("customer_pd_rule =", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleNotEqualTo(String value) {
            addCriterion("customer_pd_rule <>", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleGreaterThan(String value) {
            addCriterion("customer_pd_rule >", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleGreaterThanOrEqualTo(String value) {
            addCriterion("customer_pd_rule >=", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleLessThan(String value) {
            addCriterion("customer_pd_rule <", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleLessThanOrEqualTo(String value) {
            addCriterion("customer_pd_rule <=", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleLike(String value) {
            addCriterion("customer_pd_rule like", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleNotLike(String value) {
            addCriterion("customer_pd_rule not like", value, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleIn(List<String> values) {
            addCriterion("customer_pd_rule in", values, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleNotIn(List<String> values) {
            addCriterion("customer_pd_rule not in", values, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleBetween(String value1, String value2) {
            addCriterion("customer_pd_rule between", value1, value2, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdRuleNotBetween(String value1, String value2) {
            addCriterion("customer_pd_rule not between", value1, value2, "customerPdRule");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeIsNull() {
            addCriterion("customer_pd_size is null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeIsNotNull() {
            addCriterion("customer_pd_size is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeEqualTo(String value) {
            addCriterion("customer_pd_size =", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeNotEqualTo(String value) {
            addCriterion("customer_pd_size <>", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeGreaterThan(String value) {
            addCriterion("customer_pd_size >", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeGreaterThanOrEqualTo(String value) {
            addCriterion("customer_pd_size >=", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeLessThan(String value) {
            addCriterion("customer_pd_size <", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeLessThanOrEqualTo(String value) {
            addCriterion("customer_pd_size <=", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeLike(String value) {
            addCriterion("customer_pd_size like", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeNotLike(String value) {
            addCriterion("customer_pd_size not like", value, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeIn(List<String> values) {
            addCriterion("customer_pd_size in", values, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeNotIn(List<String> values) {
            addCriterion("customer_pd_size not in", values, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeBetween(String value1, String value2) {
            addCriterion("customer_pd_size between", value1, value2, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andCustomerPdSizeNotBetween(String value1, String value2) {
            addCriterion("customer_pd_size not between", value1, value2, "customerPdSize");
            return (Criteria) this;
        }

        public Criteria andReferencePriceIsNull() {
            addCriterion("reference_price is null");
            return (Criteria) this;
        }

        public Criteria andReferencePriceIsNotNull() {
            addCriterion("reference_price is not null");
            return (Criteria) this;
        }

        public Criteria andReferencePriceEqualTo(BigDecimal value) {
            addCriterion("reference_price =", value, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceNotEqualTo(BigDecimal value) {
            addCriterion("reference_price <>", value, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceGreaterThan(BigDecimal value) {
            addCriterion("reference_price >", value, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reference_price >=", value, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceLessThan(BigDecimal value) {
            addCriterion("reference_price <", value, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reference_price <=", value, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceIn(List<BigDecimal> values) {
            addCriterion("reference_price in", values, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceNotIn(List<BigDecimal> values) {
            addCriterion("reference_price not in", values, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reference_price between", value1, value2, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andReferencePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reference_price not between", value1, value2, "referencePrice");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationIsNull() {
            addCriterion("recent_quotation is null");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationIsNotNull() {
            addCriterion("recent_quotation is not null");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationEqualTo(BigDecimal value) {
            addCriterion("recent_quotation =", value, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationNotEqualTo(BigDecimal value) {
            addCriterion("recent_quotation <>", value, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationGreaterThan(BigDecimal value) {
            addCriterion("recent_quotation >", value, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("recent_quotation >=", value, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationLessThan(BigDecimal value) {
            addCriterion("recent_quotation <", value, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("recent_quotation <=", value, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationIn(List<BigDecimal> values) {
            addCriterion("recent_quotation in", values, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationNotIn(List<BigDecimal> values) {
            addCriterion("recent_quotation not in", values, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("recent_quotation between", value1, value2, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andRecentQuotationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("recent_quotation not between", value1, value2, "recentQuotation");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andEditUserIdIsNull() {
            addCriterion("edit_user_id is null");
            return (Criteria) this;
        }

        public Criteria andEditUserIdIsNotNull() {
            addCriterion("edit_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andEditUserIdEqualTo(String value) {
            addCriterion("edit_user_id =", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotEqualTo(String value) {
            addCriterion("edit_user_id <>", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdGreaterThan(String value) {
            addCriterion("edit_user_id >", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("edit_user_id >=", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdLessThan(String value) {
            addCriterion("edit_user_id <", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdLessThanOrEqualTo(String value) {
            addCriterion("edit_user_id <=", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdLike(String value) {
            addCriterion("edit_user_id like", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotLike(String value) {
            addCriterion("edit_user_id not like", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdIn(List<String> values) {
            addCriterion("edit_user_id in", values, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotIn(List<String> values) {
            addCriterion("edit_user_id not in", values, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdBetween(String value1, String value2) {
            addCriterion("edit_user_id between", value1, value2, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotBetween(String value1, String value2) {
            addCriterion("edit_user_id not between", value1, value2, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditTimeEqualTo(Date value) {
            addCriterion("edit_time =", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotEqualTo(Date value) {
            addCriterion("edit_time <>", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThan(Date value) {
            addCriterion("edit_time >", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_time >=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThan(Date value) {
            addCriterion("edit_time <", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_time <=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIn(List<Date> values) {
            addCriterion("edit_time in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotIn(List<Date> values) {
            addCriterion("edit_time not in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeBetween(Date value1, Date value2) {
            addCriterion("edit_time between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_time not between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andUdf1IsNull() {
            addCriterion("udf1 is null");
            return (Criteria) this;
        }

        public Criteria andUdf1IsNotNull() {
            addCriterion("udf1 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf1EqualTo(String value) {
            addCriterion("udf1 =", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotEqualTo(String value) {
            addCriterion("udf1 <>", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1GreaterThan(String value) {
            addCriterion("udf1 >", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1GreaterThanOrEqualTo(String value) {
            addCriterion("udf1 >=", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1LessThan(String value) {
            addCriterion("udf1 <", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1LessThanOrEqualTo(String value) {
            addCriterion("udf1 <=", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1Like(String value) {
            addCriterion("udf1 like", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotLike(String value) {
            addCriterion("udf1 not like", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1In(List<String> values) {
            addCriterion("udf1 in", values, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotIn(List<String> values) {
            addCriterion("udf1 not in", values, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1Between(String value1, String value2) {
            addCriterion("udf1 between", value1, value2, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotBetween(String value1, String value2) {
            addCriterion("udf1 not between", value1, value2, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf2IsNull() {
            addCriterion("udf2 is null");
            return (Criteria) this;
        }

        public Criteria andUdf2IsNotNull() {
            addCriterion("udf2 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf2EqualTo(String value) {
            addCriterion("udf2 =", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotEqualTo(String value) {
            addCriterion("udf2 <>", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2GreaterThan(String value) {
            addCriterion("udf2 >", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2GreaterThanOrEqualTo(String value) {
            addCriterion("udf2 >=", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2LessThan(String value) {
            addCriterion("udf2 <", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2LessThanOrEqualTo(String value) {
            addCriterion("udf2 <=", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2Like(String value) {
            addCriterion("udf2 like", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotLike(String value) {
            addCriterion("udf2 not like", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2In(List<String> values) {
            addCriterion("udf2 in", values, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotIn(List<String> values) {
            addCriterion("udf2 not in", values, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2Between(String value1, String value2) {
            addCriterion("udf2 between", value1, value2, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotBetween(String value1, String value2) {
            addCriterion("udf2 not between", value1, value2, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf3IsNull() {
            addCriterion("udf3 is null");
            return (Criteria) this;
        }

        public Criteria andUdf3IsNotNull() {
            addCriterion("udf3 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf3EqualTo(String value) {
            addCriterion("udf3 =", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotEqualTo(String value) {
            addCriterion("udf3 <>", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3GreaterThan(String value) {
            addCriterion("udf3 >", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3GreaterThanOrEqualTo(String value) {
            addCriterion("udf3 >=", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3LessThan(String value) {
            addCriterion("udf3 <", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3LessThanOrEqualTo(String value) {
            addCriterion("udf3 <=", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3Like(String value) {
            addCriterion("udf3 like", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotLike(String value) {
            addCriterion("udf3 not like", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3In(List<String> values) {
            addCriterion("udf3 in", values, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotIn(List<String> values) {
            addCriterion("udf3 not in", values, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3Between(String value1, String value2) {
            addCriterion("udf3 between", value1, value2, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotBetween(String value1, String value2) {
            addCriterion("udf3 not between", value1, value2, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf4IsNull() {
            addCriterion("udf4 is null");
            return (Criteria) this;
        }

        public Criteria andUdf4IsNotNull() {
            addCriterion("udf4 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf4EqualTo(String value) {
            addCriterion("udf4 =", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotEqualTo(String value) {
            addCriterion("udf4 <>", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4GreaterThan(String value) {
            addCriterion("udf4 >", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4GreaterThanOrEqualTo(String value) {
            addCriterion("udf4 >=", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4LessThan(String value) {
            addCriterion("udf4 <", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4LessThanOrEqualTo(String value) {
            addCriterion("udf4 <=", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4Like(String value) {
            addCriterion("udf4 like", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotLike(String value) {
            addCriterion("udf4 not like", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4In(List<String> values) {
            addCriterion("udf4 in", values, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotIn(List<String> values) {
            addCriterion("udf4 not in", values, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4Between(String value1, String value2) {
            addCriterion("udf4 between", value1, value2, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotBetween(String value1, String value2) {
            addCriterion("udf4 not between", value1, value2, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf5IsNull() {
            addCriterion("udf5 is null");
            return (Criteria) this;
        }

        public Criteria andUdf5IsNotNull() {
            addCriterion("udf5 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf5EqualTo(String value) {
            addCriterion("udf5 =", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotEqualTo(String value) {
            addCriterion("udf5 <>", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5GreaterThan(String value) {
            addCriterion("udf5 >", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5GreaterThanOrEqualTo(String value) {
            addCriterion("udf5 >=", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5LessThan(String value) {
            addCriterion("udf5 <", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5LessThanOrEqualTo(String value) {
            addCriterion("udf5 <=", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5Like(String value) {
            addCriterion("udf5 like", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotLike(String value) {
            addCriterion("udf5 not like", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5In(List<String> values) {
            addCriterion("udf5 in", values, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotIn(List<String> values) {
            addCriterion("udf5 not in", values, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5Between(String value1, String value2) {
            addCriterion("udf5 between", value1, value2, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotBetween(String value1, String value2) {
            addCriterion("udf5 not between", value1, value2, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf6IsNull() {
            addCriterion("udf6 is null");
            return (Criteria) this;
        }

        public Criteria andUdf6IsNotNull() {
            addCriterion("udf6 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf6EqualTo(String value) {
            addCriterion("udf6 =", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotEqualTo(String value) {
            addCriterion("udf6 <>", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6GreaterThan(String value) {
            addCriterion("udf6 >", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6GreaterThanOrEqualTo(String value) {
            addCriterion("udf6 >=", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6LessThan(String value) {
            addCriterion("udf6 <", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6LessThanOrEqualTo(String value) {
            addCriterion("udf6 <=", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6Like(String value) {
            addCriterion("udf6 like", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotLike(String value) {
            addCriterion("udf6 not like", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6In(List<String> values) {
            addCriterion("udf6 in", values, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotIn(List<String> values) {
            addCriterion("udf6 not in", values, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6Between(String value1, String value2) {
            addCriterion("udf6 between", value1, value2, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotBetween(String value1, String value2) {
            addCriterion("udf6 not between", value1, value2, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf7IsNull() {
            addCriterion("udf7 is null");
            return (Criteria) this;
        }

        public Criteria andUdf7IsNotNull() {
            addCriterion("udf7 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf7EqualTo(String value) {
            addCriterion("udf7 =", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotEqualTo(String value) {
            addCriterion("udf7 <>", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7GreaterThan(String value) {
            addCriterion("udf7 >", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7GreaterThanOrEqualTo(String value) {
            addCriterion("udf7 >=", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7LessThan(String value) {
            addCriterion("udf7 <", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7LessThanOrEqualTo(String value) {
            addCriterion("udf7 <=", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7Like(String value) {
            addCriterion("udf7 like", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotLike(String value) {
            addCriterion("udf7 not like", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7In(List<String> values) {
            addCriterion("udf7 in", values, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotIn(List<String> values) {
            addCriterion("udf7 not in", values, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7Between(String value1, String value2) {
            addCriterion("udf7 between", value1, value2, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotBetween(String value1, String value2) {
            addCriterion("udf7 not between", value1, value2, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf8IsNull() {
            addCriterion("udf8 is null");
            return (Criteria) this;
        }

        public Criteria andUdf8IsNotNull() {
            addCriterion("udf8 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf8EqualTo(String value) {
            addCriterion("udf8 =", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotEqualTo(String value) {
            addCriterion("udf8 <>", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8GreaterThan(String value) {
            addCriterion("udf8 >", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8GreaterThanOrEqualTo(String value) {
            addCriterion("udf8 >=", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8LessThan(String value) {
            addCriterion("udf8 <", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8LessThanOrEqualTo(String value) {
            addCriterion("udf8 <=", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8Like(String value) {
            addCriterion("udf8 like", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotLike(String value) {
            addCriterion("udf8 not like", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8In(List<String> values) {
            addCriterion("udf8 in", values, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotIn(List<String> values) {
            addCriterion("udf8 not in", values, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8Between(String value1, String value2) {
            addCriterion("udf8 between", value1, value2, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotBetween(String value1, String value2) {
            addCriterion("udf8 not between", value1, value2, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf9IsNull() {
            addCriterion("udf9 is null");
            return (Criteria) this;
        }

        public Criteria andUdf9IsNotNull() {
            addCriterion("udf9 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf9EqualTo(String value) {
            addCriterion("udf9 =", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotEqualTo(String value) {
            addCriterion("udf9 <>", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9GreaterThan(String value) {
            addCriterion("udf9 >", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9GreaterThanOrEqualTo(String value) {
            addCriterion("udf9 >=", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9LessThan(String value) {
            addCriterion("udf9 <", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9LessThanOrEqualTo(String value) {
            addCriterion("udf9 <=", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9Like(String value) {
            addCriterion("udf9 like", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotLike(String value) {
            addCriterion("udf9 not like", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9In(List<String> values) {
            addCriterion("udf9 in", values, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotIn(List<String> values) {
            addCriterion("udf9 not in", values, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9Between(String value1, String value2) {
            addCriterion("udf9 between", value1, value2, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotBetween(String value1, String value2) {
            addCriterion("udf9 not between", value1, value2, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf10IsNull() {
            addCriterion("udf10 is null");
            return (Criteria) this;
        }

        public Criteria andUdf10IsNotNull() {
            addCriterion("udf10 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf10EqualTo(String value) {
            addCriterion("udf10 =", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotEqualTo(String value) {
            addCriterion("udf10 <>", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10GreaterThan(String value) {
            addCriterion("udf10 >", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10GreaterThanOrEqualTo(String value) {
            addCriterion("udf10 >=", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10LessThan(String value) {
            addCriterion("udf10 <", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10LessThanOrEqualTo(String value) {
            addCriterion("udf10 <=", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10Like(String value) {
            addCriterion("udf10 like", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotLike(String value) {
            addCriterion("udf10 not like", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10In(List<String> values) {
            addCriterion("udf10 in", values, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotIn(List<String> values) {
            addCriterion("udf10 not in", values, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10Between(String value1, String value2) {
            addCriterion("udf10 between", value1, value2, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotBetween(String value1, String value2) {
            addCriterion("udf10 not between", value1, value2, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf11IsNull() {
            addCriterion("udf11 is null");
            return (Criteria) this;
        }

        public Criteria andUdf11IsNotNull() {
            addCriterion("udf11 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf11EqualTo(String value) {
            addCriterion("udf11 =", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotEqualTo(String value) {
            addCriterion("udf11 <>", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11GreaterThan(String value) {
            addCriterion("udf11 >", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11GreaterThanOrEqualTo(String value) {
            addCriterion("udf11 >=", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11LessThan(String value) {
            addCriterion("udf11 <", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11LessThanOrEqualTo(String value) {
            addCriterion("udf11 <=", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11Like(String value) {
            addCriterion("udf11 like", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotLike(String value) {
            addCriterion("udf11 not like", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11In(List<String> values) {
            addCriterion("udf11 in", values, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotIn(List<String> values) {
            addCriterion("udf11 not in", values, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11Between(String value1, String value2) {
            addCriterion("udf11 between", value1, value2, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotBetween(String value1, String value2) {
            addCriterion("udf11 not between", value1, value2, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf12IsNull() {
            addCriterion("udf12 is null");
            return (Criteria) this;
        }

        public Criteria andUdf12IsNotNull() {
            addCriterion("udf12 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf12EqualTo(String value) {
            addCriterion("udf12 =", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotEqualTo(String value) {
            addCriterion("udf12 <>", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12GreaterThan(String value) {
            addCriterion("udf12 >", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12GreaterThanOrEqualTo(String value) {
            addCriterion("udf12 >=", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12LessThan(String value) {
            addCriterion("udf12 <", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12LessThanOrEqualTo(String value) {
            addCriterion("udf12 <=", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12Like(String value) {
            addCriterion("udf12 like", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotLike(String value) {
            addCriterion("udf12 not like", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12In(List<String> values) {
            addCriterion("udf12 in", values, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotIn(List<String> values) {
            addCriterion("udf12 not in", values, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12Between(String value1, String value2) {
            addCriterion("udf12 between", value1, value2, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotBetween(String value1, String value2) {
            addCriterion("udf12 not between", value1, value2, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf13IsNull() {
            addCriterion("udf13 is null");
            return (Criteria) this;
        }

        public Criteria andUdf13IsNotNull() {
            addCriterion("udf13 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf13EqualTo(String value) {
            addCriterion("udf13 =", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotEqualTo(String value) {
            addCriterion("udf13 <>", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13GreaterThan(String value) {
            addCriterion("udf13 >", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13GreaterThanOrEqualTo(String value) {
            addCriterion("udf13 >=", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13LessThan(String value) {
            addCriterion("udf13 <", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13LessThanOrEqualTo(String value) {
            addCriterion("udf13 <=", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13Like(String value) {
            addCriterion("udf13 like", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotLike(String value) {
            addCriterion("udf13 not like", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13In(List<String> values) {
            addCriterion("udf13 in", values, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotIn(List<String> values) {
            addCriterion("udf13 not in", values, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13Between(String value1, String value2) {
            addCriterion("udf13 between", value1, value2, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotBetween(String value1, String value2) {
            addCriterion("udf13 not between", value1, value2, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf14IsNull() {
            addCriterion("udf14 is null");
            return (Criteria) this;
        }

        public Criteria andUdf14IsNotNull() {
            addCriterion("udf14 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf14EqualTo(String value) {
            addCriterion("udf14 =", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotEqualTo(String value) {
            addCriterion("udf14 <>", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14GreaterThan(String value) {
            addCriterion("udf14 >", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14GreaterThanOrEqualTo(String value) {
            addCriterion("udf14 >=", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14LessThan(String value) {
            addCriterion("udf14 <", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14LessThanOrEqualTo(String value) {
            addCriterion("udf14 <=", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14Like(String value) {
            addCriterion("udf14 like", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotLike(String value) {
            addCriterion("udf14 not like", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14In(List<String> values) {
            addCriterion("udf14 in", values, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotIn(List<String> values) {
            addCriterion("udf14 not in", values, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14Between(String value1, String value2) {
            addCriterion("udf14 between", value1, value2, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotBetween(String value1, String value2) {
            addCriterion("udf14 not between", value1, value2, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf15IsNull() {
            addCriterion("udf15 is null");
            return (Criteria) this;
        }

        public Criteria andUdf15IsNotNull() {
            addCriterion("udf15 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf15EqualTo(String value) {
            addCriterion("udf15 =", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotEqualTo(String value) {
            addCriterion("udf15 <>", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15GreaterThan(String value) {
            addCriterion("udf15 >", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15GreaterThanOrEqualTo(String value) {
            addCriterion("udf15 >=", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15LessThan(String value) {
            addCriterion("udf15 <", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15LessThanOrEqualTo(String value) {
            addCriterion("udf15 <=", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15Like(String value) {
            addCriterion("udf15 like", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotLike(String value) {
            addCriterion("udf15 not like", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15In(List<String> values) {
            addCriterion("udf15 in", values, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotIn(List<String> values) {
            addCriterion("udf15 not in", values, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15Between(String value1, String value2) {
            addCriterion("udf15 between", value1, value2, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotBetween(String value1, String value2) {
            addCriterion("udf15 not between", value1, value2, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf16IsNull() {
            addCriterion("udf16 is null");
            return (Criteria) this;
        }

        public Criteria andUdf16IsNotNull() {
            addCriterion("udf16 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf16EqualTo(String value) {
            addCriterion("udf16 =", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotEqualTo(String value) {
            addCriterion("udf16 <>", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16GreaterThan(String value) {
            addCriterion("udf16 >", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16GreaterThanOrEqualTo(String value) {
            addCriterion("udf16 >=", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16LessThan(String value) {
            addCriterion("udf16 <", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16LessThanOrEqualTo(String value) {
            addCriterion("udf16 <=", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16Like(String value) {
            addCriterion("udf16 like", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotLike(String value) {
            addCriterion("udf16 not like", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16In(List<String> values) {
            addCriterion("udf16 in", values, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotIn(List<String> values) {
            addCriterion("udf16 not in", values, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16Between(String value1, String value2) {
            addCriterion("udf16 between", value1, value2, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotBetween(String value1, String value2) {
            addCriterion("udf16 not between", value1, value2, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf17IsNull() {
            addCriterion("udf17 is null");
            return (Criteria) this;
        }

        public Criteria andUdf17IsNotNull() {
            addCriterion("udf17 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf17EqualTo(String value) {
            addCriterion("udf17 =", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotEqualTo(String value) {
            addCriterion("udf17 <>", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17GreaterThan(String value) {
            addCriterion("udf17 >", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17GreaterThanOrEqualTo(String value) {
            addCriterion("udf17 >=", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17LessThan(String value) {
            addCriterion("udf17 <", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17LessThanOrEqualTo(String value) {
            addCriterion("udf17 <=", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17Like(String value) {
            addCriterion("udf17 like", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotLike(String value) {
            addCriterion("udf17 not like", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17In(List<String> values) {
            addCriterion("udf17 in", values, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotIn(List<String> values) {
            addCriterion("udf17 not in", values, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17Between(String value1, String value2) {
            addCriterion("udf17 between", value1, value2, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotBetween(String value1, String value2) {
            addCriterion("udf17 not between", value1, value2, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf18IsNull() {
            addCriterion("udf18 is null");
            return (Criteria) this;
        }

        public Criteria andUdf18IsNotNull() {
            addCriterion("udf18 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf18EqualTo(String value) {
            addCriterion("udf18 =", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotEqualTo(String value) {
            addCriterion("udf18 <>", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18GreaterThan(String value) {
            addCriterion("udf18 >", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18GreaterThanOrEqualTo(String value) {
            addCriterion("udf18 >=", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18LessThan(String value) {
            addCriterion("udf18 <", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18LessThanOrEqualTo(String value) {
            addCriterion("udf18 <=", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18Like(String value) {
            addCriterion("udf18 like", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotLike(String value) {
            addCriterion("udf18 not like", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18In(List<String> values) {
            addCriterion("udf18 in", values, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotIn(List<String> values) {
            addCriterion("udf18 not in", values, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18Between(String value1, String value2) {
            addCriterion("udf18 between", value1, value2, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotBetween(String value1, String value2) {
            addCriterion("udf18 not between", value1, value2, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf19IsNull() {
            addCriterion("udf19 is null");
            return (Criteria) this;
        }

        public Criteria andUdf19IsNotNull() {
            addCriterion("udf19 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf19EqualTo(String value) {
            addCriterion("udf19 =", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotEqualTo(String value) {
            addCriterion("udf19 <>", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19GreaterThan(String value) {
            addCriterion("udf19 >", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19GreaterThanOrEqualTo(String value) {
            addCriterion("udf19 >=", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19LessThan(String value) {
            addCriterion("udf19 <", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19LessThanOrEqualTo(String value) {
            addCriterion("udf19 <=", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19Like(String value) {
            addCriterion("udf19 like", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotLike(String value) {
            addCriterion("udf19 not like", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19In(List<String> values) {
            addCriterion("udf19 in", values, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotIn(List<String> values) {
            addCriterion("udf19 not in", values, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19Between(String value1, String value2) {
            addCriterion("udf19 between", value1, value2, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotBetween(String value1, String value2) {
            addCriterion("udf19 not between", value1, value2, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf20IsNull() {
            addCriterion("udf20 is null");
            return (Criteria) this;
        }

        public Criteria andUdf20IsNotNull() {
            addCriterion("udf20 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf20EqualTo(String value) {
            addCriterion("udf20 =", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotEqualTo(String value) {
            addCriterion("udf20 <>", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20GreaterThan(String value) {
            addCriterion("udf20 >", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20GreaterThanOrEqualTo(String value) {
            addCriterion("udf20 >=", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20LessThan(String value) {
            addCriterion("udf20 <", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20LessThanOrEqualTo(String value) {
            addCriterion("udf20 <=", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20Like(String value) {
            addCriterion("udf20 like", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotLike(String value) {
            addCriterion("udf20 not like", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20In(List<String> values) {
            addCriterion("udf20 in", values, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotIn(List<String> values) {
            addCriterion("udf20 not in", values, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20Between(String value1, String value2) {
            addCriterion("udf20 between", value1, value2, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotBetween(String value1, String value2) {
            addCriterion("udf20 not between", value1, value2, "udf20");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_customer
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 29 15:22:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_customer
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}