package cn.evun.coreframework.model;

import java.math.BigDecimal;
import java.util.Date;

public class SkuCore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.std_product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String stdProductNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.product_name
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.product_price
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.category_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.category_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String categoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.isvalidate
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Integer isvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.approval_status
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Integer approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.channel
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Integer channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.requestId
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String requestid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf1
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf2
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf3
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf4
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf5
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf6
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf7
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf8
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf9
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf10
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf11
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf12
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf13
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf14
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf15
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf16
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf17
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf18
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf19
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf20
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf21
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf22
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf23
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf24
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_core.udf25
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String udf25;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.product_no
     *
     * @return the value of sku_core.product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.product_no
     *
     * @param productNo the value for sku_core.product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.std_product_no
     *
     * @return the value of sku_core.std_product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getStdProductNo() {
        return stdProductNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.std_product_no
     *
     * @param stdProductNo the value for sku_core.std_product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setStdProductNo(String stdProductNo) {
        this.stdProductNo = stdProductNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.product_name
     *
     * @return the value of sku_core.product_name
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.product_name
     *
     * @param productName the value for sku_core.product_name
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.product_price
     *
     * @return the value of sku_core.product_price
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.product_price
     *
     * @param productPrice the value for sku_core.product_price
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.category_id
     *
     * @return the value of sku_core.category_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.category_id
     *
     * @param categoryId the value for sku_core.category_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.category_no
     *
     * @return the value of sku_core.category_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.category_no
     *
     * @param categoryNo the value for sku_core.category_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.isvalidate
     *
     * @return the value of sku_core.isvalidate
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Integer getIsvalidate() {
        return isvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.isvalidate
     *
     * @param isvalidate the value for sku_core.isvalidate
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setIsvalidate(Integer isvalidate) {
        this.isvalidate = isvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.approval_status
     *
     * @return the value of sku_core.approval_status
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Integer getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.approval_status
     *
     * @param approvalStatus the value for sku_core.approval_status
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setApprovalStatus(Integer approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.channel
     *
     * @return the value of sku_core.channel
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.channel
     *
     * @param channel the value for sku_core.channel
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.create_user_id
     *
     * @return the value of sku_core.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.create_user_id
     *
     * @param createUserId the value for sku_core.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.create_time
     *
     * @return the value of sku_core.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.create_time
     *
     * @param createTime the value for sku_core.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.edit_user_id
     *
     * @return the value of sku_core.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.edit_user_id
     *
     * @param editUserId the value for sku_core.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.edit_time
     *
     * @return the value of sku_core.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.edit_time
     *
     * @param editTime the value for sku_core.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.requestId
     *
     * @return the value of sku_core.requestId
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getRequestid() {
        return requestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.requestId
     *
     * @param requestid the value for sku_core.requestId
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setRequestid(String requestid) {
        this.requestid = requestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf1
     *
     * @return the value of sku_core.udf1
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf1() {
        return udf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf1
     *
     * @param udf1 the value for sku_core.udf1
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf1(String udf1) {
        this.udf1 = udf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf2
     *
     * @return the value of sku_core.udf2
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf2() {
        return udf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf2
     *
     * @param udf2 the value for sku_core.udf2
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf2(String udf2) {
        this.udf2 = udf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf3
     *
     * @return the value of sku_core.udf3
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf3() {
        return udf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf3
     *
     * @param udf3 the value for sku_core.udf3
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf3(String udf3) {
        this.udf3 = udf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf4
     *
     * @return the value of sku_core.udf4
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf4() {
        return udf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf4
     *
     * @param udf4 the value for sku_core.udf4
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf4(String udf4) {
        this.udf4 = udf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf5
     *
     * @return the value of sku_core.udf5
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf5() {
        return udf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf5
     *
     * @param udf5 the value for sku_core.udf5
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf5(String udf5) {
        this.udf5 = udf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf6
     *
     * @return the value of sku_core.udf6
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf6() {
        return udf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf6
     *
     * @param udf6 the value for sku_core.udf6
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf6(String udf6) {
        this.udf6 = udf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf7
     *
     * @return the value of sku_core.udf7
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf7() {
        return udf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf7
     *
     * @param udf7 the value for sku_core.udf7
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf7(String udf7) {
        this.udf7 = udf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf8
     *
     * @return the value of sku_core.udf8
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf8() {
        return udf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf8
     *
     * @param udf8 the value for sku_core.udf8
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf8(String udf8) {
        this.udf8 = udf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf9
     *
     * @return the value of sku_core.udf9
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf9() {
        return udf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf9
     *
     * @param udf9 the value for sku_core.udf9
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf9(String udf9) {
        this.udf9 = udf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf10
     *
     * @return the value of sku_core.udf10
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf10() {
        return udf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf10
     *
     * @param udf10 the value for sku_core.udf10
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf11
     *
     * @return the value of sku_core.udf11
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf11() {
        return udf11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf11
     *
     * @param udf11 the value for sku_core.udf11
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf12
     *
     * @return the value of sku_core.udf12
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf12() {
        return udf12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf12
     *
     * @param udf12 the value for sku_core.udf12
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf13
     *
     * @return the value of sku_core.udf13
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf13() {
        return udf13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf13
     *
     * @param udf13 the value for sku_core.udf13
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf13(String udf13) {
        this.udf13 = udf13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf14
     *
     * @return the value of sku_core.udf14
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf14() {
        return udf14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf14
     *
     * @param udf14 the value for sku_core.udf14
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf14(String udf14) {
        this.udf14 = udf14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf15
     *
     * @return the value of sku_core.udf15
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf15() {
        return udf15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf15
     *
     * @param udf15 the value for sku_core.udf15
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf15(String udf15) {
        this.udf15 = udf15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf16
     *
     * @return the value of sku_core.udf16
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf16() {
        return udf16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf16
     *
     * @param udf16 the value for sku_core.udf16
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf16(String udf16) {
        this.udf16 = udf16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf17
     *
     * @return the value of sku_core.udf17
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf17() {
        return udf17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf17
     *
     * @param udf17 the value for sku_core.udf17
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf17(String udf17) {
        this.udf17 = udf17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf18
     *
     * @return the value of sku_core.udf18
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf18() {
        return udf18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf18
     *
     * @param udf18 the value for sku_core.udf18
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf18(String udf18) {
        this.udf18 = udf18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf19
     *
     * @return the value of sku_core.udf19
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf19() {
        return udf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf19
     *
     * @param udf19 the value for sku_core.udf19
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf19(String udf19) {
        this.udf19 = udf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf20
     *
     * @return the value of sku_core.udf20
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf20() {
        return udf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf20
     *
     * @param udf20 the value for sku_core.udf20
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf20(String udf20) {
        this.udf20 = udf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf21
     *
     * @return the value of sku_core.udf21
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf21() {
        return udf21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf21
     *
     * @param udf21 the value for sku_core.udf21
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf21(String udf21) {
        this.udf21 = udf21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf22
     *
     * @return the value of sku_core.udf22
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf22() {
        return udf22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf22
     *
     * @param udf22 the value for sku_core.udf22
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf22(String udf22) {
        this.udf22 = udf22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf23
     *
     * @return the value of sku_core.udf23
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf23() {
        return udf23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf23
     *
     * @param udf23 the value for sku_core.udf23
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf23(String udf23) {
        this.udf23 = udf23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf24
     *
     * @return the value of sku_core.udf24
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf24() {
        return udf24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf24
     *
     * @param udf24 the value for sku_core.udf24
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf24(String udf24) {
        this.udf24 = udf24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_core.udf25
     *
     * @return the value of sku_core.udf25
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getUdf25() {
        return udf25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_core.udf25
     *
     * @param udf25 the value for sku_core.udf25
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setUdf25(String udf25) {
        this.udf25 = udf25;
    }
}