package cn.evun.coreframework.model;

import java.math.BigDecimal;
import java.util.Date;

public class SkuPartner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.product_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.supply_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String supplyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.supply_name
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String supplyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.supply_rule
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String supplyRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.supply_size
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String supplySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.brand_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.brand_name
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.refrence_price
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private BigDecimal refrencePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.recent_enquiry
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private BigDecimal recentEnquiry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.create_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.create_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.edit_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.edit_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf1
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf2
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf3
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf4
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf5
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf6
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf7
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf8
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf9
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf10
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf11
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf12
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf13
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf14
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf15
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf16
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf17
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf18
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf19
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_partner.udf20
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String udf20;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.id
     *
     * @return the value of sku_partner.id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.id
     *
     * @param id the value for sku_partner.id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.product_no
     *
     * @return the value of sku_partner.product_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.product_no
     *
     * @param productNo the value for sku_partner.product_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.supply_no
     *
     * @return the value of sku_partner.supply_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getSupplyNo() {
        return supplyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.supply_no
     *
     * @param supplyNo the value for sku_partner.supply_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setSupplyNo(String supplyNo) {
        this.supplyNo = supplyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.supply_name
     *
     * @return the value of sku_partner.supply_name
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getSupplyName() {
        return supplyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.supply_name
     *
     * @param supplyName the value for sku_partner.supply_name
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setSupplyName(String supplyName) {
        this.supplyName = supplyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.supply_rule
     *
     * @return the value of sku_partner.supply_rule
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getSupplyRule() {
        return supplyRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.supply_rule
     *
     * @param supplyRule the value for sku_partner.supply_rule
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setSupplyRule(String supplyRule) {
        this.supplyRule = supplyRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.supply_size
     *
     * @return the value of sku_partner.supply_size
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getSupplySize() {
        return supplySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.supply_size
     *
     * @param supplySize the value for sku_partner.supply_size
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setSupplySize(String supplySize) {
        this.supplySize = supplySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.brand_id
     *
     * @return the value of sku_partner.brand_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.brand_id
     *
     * @param brandId the value for sku_partner.brand_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.brand_name
     *
     * @return the value of sku_partner.brand_name
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.brand_name
     *
     * @param brandName the value for sku_partner.brand_name
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.refrence_price
     *
     * @return the value of sku_partner.refrence_price
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public BigDecimal getRefrencePrice() {
        return refrencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.refrence_price
     *
     * @param refrencePrice the value for sku_partner.refrence_price
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setRefrencePrice(BigDecimal refrencePrice) {
        this.refrencePrice = refrencePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.recent_enquiry
     *
     * @return the value of sku_partner.recent_enquiry
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public BigDecimal getRecentEnquiry() {
        return recentEnquiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.recent_enquiry
     *
     * @param recentEnquiry the value for sku_partner.recent_enquiry
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setRecentEnquiry(BigDecimal recentEnquiry) {
        this.recentEnquiry = recentEnquiry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.create_user_id
     *
     * @return the value of sku_partner.create_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.create_user_id
     *
     * @param createUserId the value for sku_partner.create_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.create_time
     *
     * @return the value of sku_partner.create_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.create_time
     *
     * @param createTime the value for sku_partner.create_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.edit_user_id
     *
     * @return the value of sku_partner.edit_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.edit_user_id
     *
     * @param editUserId the value for sku_partner.edit_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.edit_time
     *
     * @return the value of sku_partner.edit_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.edit_time
     *
     * @param editTime the value for sku_partner.edit_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf1
     *
     * @return the value of sku_partner.udf1
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf1() {
        return udf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf1
     *
     * @param udf1 the value for sku_partner.udf1
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf1(String udf1) {
        this.udf1 = udf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf2
     *
     * @return the value of sku_partner.udf2
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf2() {
        return udf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf2
     *
     * @param udf2 the value for sku_partner.udf2
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf2(String udf2) {
        this.udf2 = udf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf3
     *
     * @return the value of sku_partner.udf3
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf3() {
        return udf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf3
     *
     * @param udf3 the value for sku_partner.udf3
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf3(String udf3) {
        this.udf3 = udf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf4
     *
     * @return the value of sku_partner.udf4
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf4() {
        return udf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf4
     *
     * @param udf4 the value for sku_partner.udf4
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf4(String udf4) {
        this.udf4 = udf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf5
     *
     * @return the value of sku_partner.udf5
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf5() {
        return udf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf5
     *
     * @param udf5 the value for sku_partner.udf5
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf5(String udf5) {
        this.udf5 = udf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf6
     *
     * @return the value of sku_partner.udf6
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf6() {
        return udf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf6
     *
     * @param udf6 the value for sku_partner.udf6
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf6(String udf6) {
        this.udf6 = udf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf7
     *
     * @return the value of sku_partner.udf7
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf7() {
        return udf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf7
     *
     * @param udf7 the value for sku_partner.udf7
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf7(String udf7) {
        this.udf7 = udf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf8
     *
     * @return the value of sku_partner.udf8
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf8() {
        return udf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf8
     *
     * @param udf8 the value for sku_partner.udf8
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf8(String udf8) {
        this.udf8 = udf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf9
     *
     * @return the value of sku_partner.udf9
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf9() {
        return udf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf9
     *
     * @param udf9 the value for sku_partner.udf9
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf9(String udf9) {
        this.udf9 = udf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf10
     *
     * @return the value of sku_partner.udf10
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf10() {
        return udf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf10
     *
     * @param udf10 the value for sku_partner.udf10
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf10(String udf10) {
        this.udf10 = udf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf11
     *
     * @return the value of sku_partner.udf11
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf11() {
        return udf11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf11
     *
     * @param udf11 the value for sku_partner.udf11
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf11(String udf11) {
        this.udf11 = udf11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf12
     *
     * @return the value of sku_partner.udf12
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf12() {
        return udf12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf12
     *
     * @param udf12 the value for sku_partner.udf12
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf12(String udf12) {
        this.udf12 = udf12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf13
     *
     * @return the value of sku_partner.udf13
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf13() {
        return udf13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf13
     *
     * @param udf13 the value for sku_partner.udf13
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf13(String udf13) {
        this.udf13 = udf13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf14
     *
     * @return the value of sku_partner.udf14
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf14() {
        return udf14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf14
     *
     * @param udf14 the value for sku_partner.udf14
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf14(String udf14) {
        this.udf14 = udf14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf15
     *
     * @return the value of sku_partner.udf15
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf15() {
        return udf15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf15
     *
     * @param udf15 the value for sku_partner.udf15
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf15(String udf15) {
        this.udf15 = udf15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf16
     *
     * @return the value of sku_partner.udf16
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf16() {
        return udf16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf16
     *
     * @param udf16 the value for sku_partner.udf16
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf16(String udf16) {
        this.udf16 = udf16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf17
     *
     * @return the value of sku_partner.udf17
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf17() {
        return udf17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf17
     *
     * @param udf17 the value for sku_partner.udf17
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf17(String udf17) {
        this.udf17 = udf17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf18
     *
     * @return the value of sku_partner.udf18
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf18() {
        return udf18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf18
     *
     * @param udf18 the value for sku_partner.udf18
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf18(String udf18) {
        this.udf18 = udf18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf19
     *
     * @return the value of sku_partner.udf19
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf19() {
        return udf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf19
     *
     * @param udf19 the value for sku_partner.udf19
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf19(String udf19) {
        this.udf19 = udf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_partner.udf20
     *
     * @return the value of sku_partner.udf20
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getUdf20() {
        return udf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_partner.udf20
     *
     * @param udf20 the value for sku_partner.udf20
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setUdf20(String udf20) {
        this.udf20 = udf20;
    }
}