package cn.evun.coreframework.model;

import java.math.BigDecimal;
import java.util.Date;

public class SkuSell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.product_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.sell_price
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private BigDecimal sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.description
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.create_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.create_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.edit_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.edit_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.opt_udf_1
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String optUdf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.opt_udf_2
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String optUdf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_sell.opt_udf_3
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    private String optUdf3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.id
     *
     * @return the value of sku_sell.id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.id
     *
     * @param id the value for sku_sell.id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.product_no
     *
     * @return the value of sku_sell.product_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.product_no
     *
     * @param productNo the value for sku_sell.product_no
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.sell_price
     *
     * @return the value of sku_sell.sell_price
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.sell_price
     *
     * @param sellPrice the value for sku_sell.sell_price
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.description
     *
     * @return the value of sku_sell.description
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.description
     *
     * @param description the value for sku_sell.description
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.create_user_id
     *
     * @return the value of sku_sell.create_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.create_user_id
     *
     * @param createUserId the value for sku_sell.create_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.create_time
     *
     * @return the value of sku_sell.create_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.create_time
     *
     * @param createTime the value for sku_sell.create_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.edit_user_id
     *
     * @return the value of sku_sell.edit_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.edit_user_id
     *
     * @param editUserId the value for sku_sell.edit_user_id
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.edit_time
     *
     * @return the value of sku_sell.edit_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.edit_time
     *
     * @param editTime the value for sku_sell.edit_time
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.opt_udf_1
     *
     * @return the value of sku_sell.opt_udf_1
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getOptUdf1() {
        return optUdf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.opt_udf_1
     *
     * @param optUdf1 the value for sku_sell.opt_udf_1
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setOptUdf1(String optUdf1) {
        this.optUdf1 = optUdf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.opt_udf_2
     *
     * @return the value of sku_sell.opt_udf_2
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getOptUdf2() {
        return optUdf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.opt_udf_2
     *
     * @param optUdf2 the value for sku_sell.opt_udf_2
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setOptUdf2(String optUdf2) {
        this.optUdf2 = optUdf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_sell.opt_udf_3
     *
     * @return the value of sku_sell.opt_udf_3
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getOptUdf3() {
        return optUdf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_sell.opt_udf_3
     *
     * @param optUdf3 the value for sku_sell.opt_udf_3
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setOptUdf3(String optUdf3) {
        this.optUdf3 = optUdf3;
    }
}