package cn.evun.coreframework.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkuUomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public SkuUomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNull() {
            addCriterion("product_no is null");
            return (Criteria) this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("product_no is not null");
            return (Criteria) this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("product_no =", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("product_no <>", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("product_no >", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("product_no >=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("product_no <", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("product_no <=", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("product_no like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("product_no not like", value, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoIn(List<String> values) {
            addCriterion("product_no in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotIn(List<String> values) {
            addCriterion("product_no not in", values, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("product_no between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("product_no not between", value1, value2, "productNo");
            return (Criteria) this;
        }

        public Criteria andPackNoIsNull() {
            addCriterion("pack_no is null");
            return (Criteria) this;
        }

        public Criteria andPackNoIsNotNull() {
            addCriterion("pack_no is not null");
            return (Criteria) this;
        }

        public Criteria andPackNoEqualTo(String value) {
            addCriterion("pack_no =", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoNotEqualTo(String value) {
            addCriterion("pack_no <>", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoGreaterThan(String value) {
            addCriterion("pack_no >", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoGreaterThanOrEqualTo(String value) {
            addCriterion("pack_no >=", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoLessThan(String value) {
            addCriterion("pack_no <", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoLessThanOrEqualTo(String value) {
            addCriterion("pack_no <=", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoLike(String value) {
            addCriterion("pack_no like", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoNotLike(String value) {
            addCriterion("pack_no not like", value, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoIn(List<String> values) {
            addCriterion("pack_no in", values, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoNotIn(List<String> values) {
            addCriterion("pack_no not in", values, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoBetween(String value1, String value2) {
            addCriterion("pack_no between", value1, value2, "packNo");
            return (Criteria) this;
        }

        public Criteria andPackNoNotBetween(String value1, String value2) {
            addCriterion("pack_no not between", value1, value2, "packNo");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameIsNull() {
            addCriterion("inv_unit_name is null");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameIsNotNull() {
            addCriterion("inv_unit_name is not null");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameEqualTo(String value) {
            addCriterion("inv_unit_name =", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameNotEqualTo(String value) {
            addCriterion("inv_unit_name <>", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameGreaterThan(String value) {
            addCriterion("inv_unit_name >", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("inv_unit_name >=", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameLessThan(String value) {
            addCriterion("inv_unit_name <", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameLessThanOrEqualTo(String value) {
            addCriterion("inv_unit_name <=", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameLike(String value) {
            addCriterion("inv_unit_name like", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameNotLike(String value) {
            addCriterion("inv_unit_name not like", value, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameIn(List<String> values) {
            addCriterion("inv_unit_name in", values, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameNotIn(List<String> values) {
            addCriterion("inv_unit_name not in", values, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameBetween(String value1, String value2) {
            addCriterion("inv_unit_name between", value1, value2, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andInvUnitNameNotBetween(String value1, String value2) {
            addCriterion("inv_unit_name not between", value1, value2, "invUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameIsNull() {
            addCriterion("pack_unit_name is null");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameIsNotNull() {
            addCriterion("pack_unit_name is not null");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameEqualTo(String value) {
            addCriterion("pack_unit_name =", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameNotEqualTo(String value) {
            addCriterion("pack_unit_name <>", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameGreaterThan(String value) {
            addCriterion("pack_unit_name >", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("pack_unit_name >=", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameLessThan(String value) {
            addCriterion("pack_unit_name <", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameLessThanOrEqualTo(String value) {
            addCriterion("pack_unit_name <=", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameLike(String value) {
            addCriterion("pack_unit_name like", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameNotLike(String value) {
            addCriterion("pack_unit_name not like", value, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameIn(List<String> values) {
            addCriterion("pack_unit_name in", values, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameNotIn(List<String> values) {
            addCriterion("pack_unit_name not in", values, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameBetween(String value1, String value2) {
            addCriterion("pack_unit_name between", value1, value2, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackUnitNameNotBetween(String value1, String value2) {
            addCriterion("pack_unit_name not between", value1, value2, "packUnitName");
            return (Criteria) this;
        }

        public Criteria andPackRateIsNull() {
            addCriterion("pack_rate is null");
            return (Criteria) this;
        }

        public Criteria andPackRateIsNotNull() {
            addCriterion("pack_rate is not null");
            return (Criteria) this;
        }

        public Criteria andPackRateEqualTo(BigDecimal value) {
            addCriterion("pack_rate =", value, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateNotEqualTo(BigDecimal value) {
            addCriterion("pack_rate <>", value, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateGreaterThan(BigDecimal value) {
            addCriterion("pack_rate >", value, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pack_rate >=", value, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateLessThan(BigDecimal value) {
            addCriterion("pack_rate <", value, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pack_rate <=", value, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateIn(List<BigDecimal> values) {
            addCriterion("pack_rate in", values, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateNotIn(List<BigDecimal> values) {
            addCriterion("pack_rate not in", values, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pack_rate between", value1, value2, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pack_rate not between", value1, value2, "packRate");
            return (Criteria) this;
        }

        public Criteria andPackStandardIsNull() {
            addCriterion("pack_standard is null");
            return (Criteria) this;
        }

        public Criteria andPackStandardIsNotNull() {
            addCriterion("pack_standard is not null");
            return (Criteria) this;
        }

        public Criteria andPackStandardEqualTo(String value) {
            addCriterion("pack_standard =", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardNotEqualTo(String value) {
            addCriterion("pack_standard <>", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardGreaterThan(String value) {
            addCriterion("pack_standard >", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardGreaterThanOrEqualTo(String value) {
            addCriterion("pack_standard >=", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardLessThan(String value) {
            addCriterion("pack_standard <", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardLessThanOrEqualTo(String value) {
            addCriterion("pack_standard <=", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardLike(String value) {
            addCriterion("pack_standard like", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardNotLike(String value) {
            addCriterion("pack_standard not like", value, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardIn(List<String> values) {
            addCriterion("pack_standard in", values, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardNotIn(List<String> values) {
            addCriterion("pack_standard not in", values, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardBetween(String value1, String value2) {
            addCriterion("pack_standard between", value1, value2, "packStandard");
            return (Criteria) this;
        }

        public Criteria andPackStandardNotBetween(String value1, String value2) {
            addCriterion("pack_standard not between", value1, value2, "packStandard");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceIsNull() {
            addCriterion("std_zy_price is null");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceIsNotNull() {
            addCriterion("std_zy_price is not null");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceEqualTo(BigDecimal value) {
            addCriterion("std_zy_price =", value, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceNotEqualTo(BigDecimal value) {
            addCriterion("std_zy_price <>", value, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceGreaterThan(BigDecimal value) {
            addCriterion("std_zy_price >", value, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("std_zy_price >=", value, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceLessThan(BigDecimal value) {
            addCriterion("std_zy_price <", value, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("std_zy_price <=", value, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceIn(List<BigDecimal> values) {
            addCriterion("std_zy_price in", values, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceNotIn(List<BigDecimal> values) {
            addCriterion("std_zy_price not in", values, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_zy_price between", value1, value2, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andStdZyPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("std_zy_price not between", value1, value2, "stdZyPrice");
            return (Criteria) this;
        }

        public Criteria andPcsLengthIsNull() {
            addCriterion("pcs_length is null");
            return (Criteria) this;
        }

        public Criteria andPcsLengthIsNotNull() {
            addCriterion("pcs_length is not null");
            return (Criteria) this;
        }

        public Criteria andPcsLengthEqualTo(BigDecimal value) {
            addCriterion("pcs_length =", value, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthNotEqualTo(BigDecimal value) {
            addCriterion("pcs_length <>", value, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthGreaterThan(BigDecimal value) {
            addCriterion("pcs_length >", value, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pcs_length >=", value, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthLessThan(BigDecimal value) {
            addCriterion("pcs_length <", value, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pcs_length <=", value, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthIn(List<BigDecimal> values) {
            addCriterion("pcs_length in", values, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthNotIn(List<BigDecimal> values) {
            addCriterion("pcs_length not in", values, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pcs_length between", value1, value2, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsLengthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pcs_length not between", value1, value2, "pcsLength");
            return (Criteria) this;
        }

        public Criteria andPcsWidthIsNull() {
            addCriterion("pcs_width is null");
            return (Criteria) this;
        }

        public Criteria andPcsWidthIsNotNull() {
            addCriterion("pcs_width is not null");
            return (Criteria) this;
        }

        public Criteria andPcsWidthEqualTo(BigDecimal value) {
            addCriterion("pcs_width =", value, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthNotEqualTo(BigDecimal value) {
            addCriterion("pcs_width <>", value, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthGreaterThan(BigDecimal value) {
            addCriterion("pcs_width >", value, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pcs_width >=", value, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthLessThan(BigDecimal value) {
            addCriterion("pcs_width <", value, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pcs_width <=", value, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthIn(List<BigDecimal> values) {
            addCriterion("pcs_width in", values, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthNotIn(List<BigDecimal> values) {
            addCriterion("pcs_width not in", values, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pcs_width between", value1, value2, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsWidthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pcs_width not between", value1, value2, "pcsWidth");
            return (Criteria) this;
        }

        public Criteria andPcsHeightIsNull() {
            addCriterion("pcs_height is null");
            return (Criteria) this;
        }

        public Criteria andPcsHeightIsNotNull() {
            addCriterion("pcs_height is not null");
            return (Criteria) this;
        }

        public Criteria andPcsHeightEqualTo(BigDecimal value) {
            addCriterion("pcs_height =", value, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightNotEqualTo(BigDecimal value) {
            addCriterion("pcs_height <>", value, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightGreaterThan(BigDecimal value) {
            addCriterion("pcs_height >", value, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pcs_height >=", value, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightLessThan(BigDecimal value) {
            addCriterion("pcs_height <", value, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pcs_height <=", value, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightIn(List<BigDecimal> values) {
            addCriterion("pcs_height in", values, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightNotIn(List<BigDecimal> values) {
            addCriterion("pcs_height not in", values, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pcs_height between", value1, value2, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andPcsHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pcs_height not between", value1, value2, "pcsHeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightIsNull() {
            addCriterion("net_weight is null");
            return (Criteria) this;
        }

        public Criteria andNetWeightIsNotNull() {
            addCriterion("net_weight is not null");
            return (Criteria) this;
        }

        public Criteria andNetWeightEqualTo(Double value) {
            addCriterion("net_weight =", value, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightNotEqualTo(Double value) {
            addCriterion("net_weight <>", value, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightGreaterThan(Double value) {
            addCriterion("net_weight >", value, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("net_weight >=", value, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightLessThan(Double value) {
            addCriterion("net_weight <", value, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightLessThanOrEqualTo(Double value) {
            addCriterion("net_weight <=", value, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightIn(List<Double> values) {
            addCriterion("net_weight in", values, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightNotIn(List<Double> values) {
            addCriterion("net_weight not in", values, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightBetween(Double value1, Double value2) {
            addCriterion("net_weight between", value1, value2, "netWeight");
            return (Criteria) this;
        }

        public Criteria andNetWeightNotBetween(Double value1, Double value2) {
            addCriterion("net_weight not between", value1, value2, "netWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightIsNull() {
            addCriterion("gross_weight is null");
            return (Criteria) this;
        }

        public Criteria andGrossWeightIsNotNull() {
            addCriterion("gross_weight is not null");
            return (Criteria) this;
        }

        public Criteria andGrossWeightEqualTo(Double value) {
            addCriterion("gross_weight =", value, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightNotEqualTo(Double value) {
            addCriterion("gross_weight <>", value, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightGreaterThan(Double value) {
            addCriterion("gross_weight >", value, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("gross_weight >=", value, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightLessThan(Double value) {
            addCriterion("gross_weight <", value, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightLessThanOrEqualTo(Double value) {
            addCriterion("gross_weight <=", value, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightIn(List<Double> values) {
            addCriterion("gross_weight in", values, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightNotIn(List<Double> values) {
            addCriterion("gross_weight not in", values, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightBetween(Double value1, Double value2) {
            addCriterion("gross_weight between", value1, value2, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andGrossWeightNotBetween(Double value1, Double value2) {
            addCriterion("gross_weight not between", value1, value2, "grossWeight");
            return (Criteria) this;
        }

        public Criteria andSizeTypeIsNull() {
            addCriterion("size_type is null");
            return (Criteria) this;
        }

        public Criteria andSizeTypeIsNotNull() {
            addCriterion("size_type is not null");
            return (Criteria) this;
        }

        public Criteria andSizeTypeEqualTo(String value) {
            addCriterion("size_type =", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeNotEqualTo(String value) {
            addCriterion("size_type <>", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeGreaterThan(String value) {
            addCriterion("size_type >", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("size_type >=", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeLessThan(String value) {
            addCriterion("size_type <", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeLessThanOrEqualTo(String value) {
            addCriterion("size_type <=", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeLike(String value) {
            addCriterion("size_type like", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeNotLike(String value) {
            addCriterion("size_type not like", value, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeIn(List<String> values) {
            addCriterion("size_type in", values, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeNotIn(List<String> values) {
            addCriterion("size_type not in", values, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeBetween(String value1, String value2) {
            addCriterion("size_type between", value1, value2, "sizeType");
            return (Criteria) this;
        }

        public Criteria andSizeTypeNotBetween(String value1, String value2) {
            addCriterion("size_type not between", value1, value2, "sizeType");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("create_user_id like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("create_user_id not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andEditUserIdIsNull() {
            addCriterion("edit_user_id is null");
            return (Criteria) this;
        }

        public Criteria andEditUserIdIsNotNull() {
            addCriterion("edit_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andEditUserIdEqualTo(String value) {
            addCriterion("edit_user_id =", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotEqualTo(String value) {
            addCriterion("edit_user_id <>", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdGreaterThan(String value) {
            addCriterion("edit_user_id >", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("edit_user_id >=", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdLessThan(String value) {
            addCriterion("edit_user_id <", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdLessThanOrEqualTo(String value) {
            addCriterion("edit_user_id <=", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdLike(String value) {
            addCriterion("edit_user_id like", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotLike(String value) {
            addCriterion("edit_user_id not like", value, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdIn(List<String> values) {
            addCriterion("edit_user_id in", values, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotIn(List<String> values) {
            addCriterion("edit_user_id not in", values, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdBetween(String value1, String value2) {
            addCriterion("edit_user_id between", value1, value2, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditUserIdNotBetween(String value1, String value2) {
            addCriterion("edit_user_id not between", value1, value2, "editUserId");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNull() {
            addCriterion("edit_time is null");
            return (Criteria) this;
        }

        public Criteria andEditTimeIsNotNull() {
            addCriterion("edit_time is not null");
            return (Criteria) this;
        }

        public Criteria andEditTimeEqualTo(Date value) {
            addCriterion("edit_time =", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotEqualTo(Date value) {
            addCriterion("edit_time <>", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThan(Date value) {
            addCriterion("edit_time >", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("edit_time >=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThan(Date value) {
            addCriterion("edit_time <", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeLessThanOrEqualTo(Date value) {
            addCriterion("edit_time <=", value, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeIn(List<Date> values) {
            addCriterion("edit_time in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotIn(List<Date> values) {
            addCriterion("edit_time not in", values, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeBetween(Date value1, Date value2) {
            addCriterion("edit_time between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andEditTimeNotBetween(Date value1, Date value2) {
            addCriterion("edit_time not between", value1, value2, "editTime");
            return (Criteria) this;
        }

        public Criteria andUdf1IsNull() {
            addCriterion("udf1 is null");
            return (Criteria) this;
        }

        public Criteria andUdf1IsNotNull() {
            addCriterion("udf1 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf1EqualTo(String value) {
            addCriterion("udf1 =", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotEqualTo(String value) {
            addCriterion("udf1 <>", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1GreaterThan(String value) {
            addCriterion("udf1 >", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1GreaterThanOrEqualTo(String value) {
            addCriterion("udf1 >=", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1LessThan(String value) {
            addCriterion("udf1 <", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1LessThanOrEqualTo(String value) {
            addCriterion("udf1 <=", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1Like(String value) {
            addCriterion("udf1 like", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotLike(String value) {
            addCriterion("udf1 not like", value, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1In(List<String> values) {
            addCriterion("udf1 in", values, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotIn(List<String> values) {
            addCriterion("udf1 not in", values, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1Between(String value1, String value2) {
            addCriterion("udf1 between", value1, value2, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf1NotBetween(String value1, String value2) {
            addCriterion("udf1 not between", value1, value2, "udf1");
            return (Criteria) this;
        }

        public Criteria andUdf2IsNull() {
            addCriterion("udf2 is null");
            return (Criteria) this;
        }

        public Criteria andUdf2IsNotNull() {
            addCriterion("udf2 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf2EqualTo(String value) {
            addCriterion("udf2 =", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotEqualTo(String value) {
            addCriterion("udf2 <>", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2GreaterThan(String value) {
            addCriterion("udf2 >", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2GreaterThanOrEqualTo(String value) {
            addCriterion("udf2 >=", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2LessThan(String value) {
            addCriterion("udf2 <", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2LessThanOrEqualTo(String value) {
            addCriterion("udf2 <=", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2Like(String value) {
            addCriterion("udf2 like", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotLike(String value) {
            addCriterion("udf2 not like", value, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2In(List<String> values) {
            addCriterion("udf2 in", values, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotIn(List<String> values) {
            addCriterion("udf2 not in", values, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2Between(String value1, String value2) {
            addCriterion("udf2 between", value1, value2, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf2NotBetween(String value1, String value2) {
            addCriterion("udf2 not between", value1, value2, "udf2");
            return (Criteria) this;
        }

        public Criteria andUdf3IsNull() {
            addCriterion("udf3 is null");
            return (Criteria) this;
        }

        public Criteria andUdf3IsNotNull() {
            addCriterion("udf3 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf3EqualTo(String value) {
            addCriterion("udf3 =", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotEqualTo(String value) {
            addCriterion("udf3 <>", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3GreaterThan(String value) {
            addCriterion("udf3 >", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3GreaterThanOrEqualTo(String value) {
            addCriterion("udf3 >=", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3LessThan(String value) {
            addCriterion("udf3 <", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3LessThanOrEqualTo(String value) {
            addCriterion("udf3 <=", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3Like(String value) {
            addCriterion("udf3 like", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotLike(String value) {
            addCriterion("udf3 not like", value, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3In(List<String> values) {
            addCriterion("udf3 in", values, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotIn(List<String> values) {
            addCriterion("udf3 not in", values, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3Between(String value1, String value2) {
            addCriterion("udf3 between", value1, value2, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf3NotBetween(String value1, String value2) {
            addCriterion("udf3 not between", value1, value2, "udf3");
            return (Criteria) this;
        }

        public Criteria andUdf4IsNull() {
            addCriterion("udf4 is null");
            return (Criteria) this;
        }

        public Criteria andUdf4IsNotNull() {
            addCriterion("udf4 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf4EqualTo(String value) {
            addCriterion("udf4 =", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotEqualTo(String value) {
            addCriterion("udf4 <>", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4GreaterThan(String value) {
            addCriterion("udf4 >", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4GreaterThanOrEqualTo(String value) {
            addCriterion("udf4 >=", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4LessThan(String value) {
            addCriterion("udf4 <", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4LessThanOrEqualTo(String value) {
            addCriterion("udf4 <=", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4Like(String value) {
            addCriterion("udf4 like", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotLike(String value) {
            addCriterion("udf4 not like", value, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4In(List<String> values) {
            addCriterion("udf4 in", values, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotIn(List<String> values) {
            addCriterion("udf4 not in", values, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4Between(String value1, String value2) {
            addCriterion("udf4 between", value1, value2, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf4NotBetween(String value1, String value2) {
            addCriterion("udf4 not between", value1, value2, "udf4");
            return (Criteria) this;
        }

        public Criteria andUdf5IsNull() {
            addCriterion("udf5 is null");
            return (Criteria) this;
        }

        public Criteria andUdf5IsNotNull() {
            addCriterion("udf5 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf5EqualTo(String value) {
            addCriterion("udf5 =", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotEqualTo(String value) {
            addCriterion("udf5 <>", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5GreaterThan(String value) {
            addCriterion("udf5 >", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5GreaterThanOrEqualTo(String value) {
            addCriterion("udf5 >=", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5LessThan(String value) {
            addCriterion("udf5 <", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5LessThanOrEqualTo(String value) {
            addCriterion("udf5 <=", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5Like(String value) {
            addCriterion("udf5 like", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotLike(String value) {
            addCriterion("udf5 not like", value, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5In(List<String> values) {
            addCriterion("udf5 in", values, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotIn(List<String> values) {
            addCriterion("udf5 not in", values, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5Between(String value1, String value2) {
            addCriterion("udf5 between", value1, value2, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf5NotBetween(String value1, String value2) {
            addCriterion("udf5 not between", value1, value2, "udf5");
            return (Criteria) this;
        }

        public Criteria andUdf6IsNull() {
            addCriterion("udf6 is null");
            return (Criteria) this;
        }

        public Criteria andUdf6IsNotNull() {
            addCriterion("udf6 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf6EqualTo(String value) {
            addCriterion("udf6 =", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotEqualTo(String value) {
            addCriterion("udf6 <>", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6GreaterThan(String value) {
            addCriterion("udf6 >", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6GreaterThanOrEqualTo(String value) {
            addCriterion("udf6 >=", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6LessThan(String value) {
            addCriterion("udf6 <", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6LessThanOrEqualTo(String value) {
            addCriterion("udf6 <=", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6Like(String value) {
            addCriterion("udf6 like", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotLike(String value) {
            addCriterion("udf6 not like", value, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6In(List<String> values) {
            addCriterion("udf6 in", values, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotIn(List<String> values) {
            addCriterion("udf6 not in", values, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6Between(String value1, String value2) {
            addCriterion("udf6 between", value1, value2, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf6NotBetween(String value1, String value2) {
            addCriterion("udf6 not between", value1, value2, "udf6");
            return (Criteria) this;
        }

        public Criteria andUdf7IsNull() {
            addCriterion("udf7 is null");
            return (Criteria) this;
        }

        public Criteria andUdf7IsNotNull() {
            addCriterion("udf7 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf7EqualTo(String value) {
            addCriterion("udf7 =", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotEqualTo(String value) {
            addCriterion("udf7 <>", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7GreaterThan(String value) {
            addCriterion("udf7 >", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7GreaterThanOrEqualTo(String value) {
            addCriterion("udf7 >=", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7LessThan(String value) {
            addCriterion("udf7 <", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7LessThanOrEqualTo(String value) {
            addCriterion("udf7 <=", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7Like(String value) {
            addCriterion("udf7 like", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotLike(String value) {
            addCriterion("udf7 not like", value, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7In(List<String> values) {
            addCriterion("udf7 in", values, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotIn(List<String> values) {
            addCriterion("udf7 not in", values, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7Between(String value1, String value2) {
            addCriterion("udf7 between", value1, value2, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf7NotBetween(String value1, String value2) {
            addCriterion("udf7 not between", value1, value2, "udf7");
            return (Criteria) this;
        }

        public Criteria andUdf8IsNull() {
            addCriterion("udf8 is null");
            return (Criteria) this;
        }

        public Criteria andUdf8IsNotNull() {
            addCriterion("udf8 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf8EqualTo(String value) {
            addCriterion("udf8 =", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotEqualTo(String value) {
            addCriterion("udf8 <>", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8GreaterThan(String value) {
            addCriterion("udf8 >", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8GreaterThanOrEqualTo(String value) {
            addCriterion("udf8 >=", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8LessThan(String value) {
            addCriterion("udf8 <", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8LessThanOrEqualTo(String value) {
            addCriterion("udf8 <=", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8Like(String value) {
            addCriterion("udf8 like", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotLike(String value) {
            addCriterion("udf8 not like", value, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8In(List<String> values) {
            addCriterion("udf8 in", values, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotIn(List<String> values) {
            addCriterion("udf8 not in", values, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8Between(String value1, String value2) {
            addCriterion("udf8 between", value1, value2, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf8NotBetween(String value1, String value2) {
            addCriterion("udf8 not between", value1, value2, "udf8");
            return (Criteria) this;
        }

        public Criteria andUdf9IsNull() {
            addCriterion("udf9 is null");
            return (Criteria) this;
        }

        public Criteria andUdf9IsNotNull() {
            addCriterion("udf9 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf9EqualTo(String value) {
            addCriterion("udf9 =", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotEqualTo(String value) {
            addCriterion("udf9 <>", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9GreaterThan(String value) {
            addCriterion("udf9 >", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9GreaterThanOrEqualTo(String value) {
            addCriterion("udf9 >=", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9LessThan(String value) {
            addCriterion("udf9 <", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9LessThanOrEqualTo(String value) {
            addCriterion("udf9 <=", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9Like(String value) {
            addCriterion("udf9 like", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotLike(String value) {
            addCriterion("udf9 not like", value, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9In(List<String> values) {
            addCriterion("udf9 in", values, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotIn(List<String> values) {
            addCriterion("udf9 not in", values, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9Between(String value1, String value2) {
            addCriterion("udf9 between", value1, value2, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf9NotBetween(String value1, String value2) {
            addCriterion("udf9 not between", value1, value2, "udf9");
            return (Criteria) this;
        }

        public Criteria andUdf10IsNull() {
            addCriterion("udf10 is null");
            return (Criteria) this;
        }

        public Criteria andUdf10IsNotNull() {
            addCriterion("udf10 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf10EqualTo(String value) {
            addCriterion("udf10 =", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotEqualTo(String value) {
            addCriterion("udf10 <>", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10GreaterThan(String value) {
            addCriterion("udf10 >", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10GreaterThanOrEqualTo(String value) {
            addCriterion("udf10 >=", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10LessThan(String value) {
            addCriterion("udf10 <", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10LessThanOrEqualTo(String value) {
            addCriterion("udf10 <=", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10Like(String value) {
            addCriterion("udf10 like", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotLike(String value) {
            addCriterion("udf10 not like", value, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10In(List<String> values) {
            addCriterion("udf10 in", values, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotIn(List<String> values) {
            addCriterion("udf10 not in", values, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10Between(String value1, String value2) {
            addCriterion("udf10 between", value1, value2, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf10NotBetween(String value1, String value2) {
            addCriterion("udf10 not between", value1, value2, "udf10");
            return (Criteria) this;
        }

        public Criteria andUdf11IsNull() {
            addCriterion("udf11 is null");
            return (Criteria) this;
        }

        public Criteria andUdf11IsNotNull() {
            addCriterion("udf11 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf11EqualTo(String value) {
            addCriterion("udf11 =", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotEqualTo(String value) {
            addCriterion("udf11 <>", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11GreaterThan(String value) {
            addCriterion("udf11 >", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11GreaterThanOrEqualTo(String value) {
            addCriterion("udf11 >=", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11LessThan(String value) {
            addCriterion("udf11 <", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11LessThanOrEqualTo(String value) {
            addCriterion("udf11 <=", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11Like(String value) {
            addCriterion("udf11 like", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotLike(String value) {
            addCriterion("udf11 not like", value, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11In(List<String> values) {
            addCriterion("udf11 in", values, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotIn(List<String> values) {
            addCriterion("udf11 not in", values, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11Between(String value1, String value2) {
            addCriterion("udf11 between", value1, value2, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf11NotBetween(String value1, String value2) {
            addCriterion("udf11 not between", value1, value2, "udf11");
            return (Criteria) this;
        }

        public Criteria andUdf12IsNull() {
            addCriterion("udf12 is null");
            return (Criteria) this;
        }

        public Criteria andUdf12IsNotNull() {
            addCriterion("udf12 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf12EqualTo(String value) {
            addCriterion("udf12 =", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotEqualTo(String value) {
            addCriterion("udf12 <>", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12GreaterThan(String value) {
            addCriterion("udf12 >", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12GreaterThanOrEqualTo(String value) {
            addCriterion("udf12 >=", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12LessThan(String value) {
            addCriterion("udf12 <", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12LessThanOrEqualTo(String value) {
            addCriterion("udf12 <=", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12Like(String value) {
            addCriterion("udf12 like", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotLike(String value) {
            addCriterion("udf12 not like", value, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12In(List<String> values) {
            addCriterion("udf12 in", values, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotIn(List<String> values) {
            addCriterion("udf12 not in", values, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12Between(String value1, String value2) {
            addCriterion("udf12 between", value1, value2, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf12NotBetween(String value1, String value2) {
            addCriterion("udf12 not between", value1, value2, "udf12");
            return (Criteria) this;
        }

        public Criteria andUdf13IsNull() {
            addCriterion("udf13 is null");
            return (Criteria) this;
        }

        public Criteria andUdf13IsNotNull() {
            addCriterion("udf13 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf13EqualTo(String value) {
            addCriterion("udf13 =", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotEqualTo(String value) {
            addCriterion("udf13 <>", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13GreaterThan(String value) {
            addCriterion("udf13 >", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13GreaterThanOrEqualTo(String value) {
            addCriterion("udf13 >=", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13LessThan(String value) {
            addCriterion("udf13 <", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13LessThanOrEqualTo(String value) {
            addCriterion("udf13 <=", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13Like(String value) {
            addCriterion("udf13 like", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotLike(String value) {
            addCriterion("udf13 not like", value, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13In(List<String> values) {
            addCriterion("udf13 in", values, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotIn(List<String> values) {
            addCriterion("udf13 not in", values, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13Between(String value1, String value2) {
            addCriterion("udf13 between", value1, value2, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf13NotBetween(String value1, String value2) {
            addCriterion("udf13 not between", value1, value2, "udf13");
            return (Criteria) this;
        }

        public Criteria andUdf14IsNull() {
            addCriterion("udf14 is null");
            return (Criteria) this;
        }

        public Criteria andUdf14IsNotNull() {
            addCriterion("udf14 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf14EqualTo(String value) {
            addCriterion("udf14 =", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotEqualTo(String value) {
            addCriterion("udf14 <>", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14GreaterThan(String value) {
            addCriterion("udf14 >", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14GreaterThanOrEqualTo(String value) {
            addCriterion("udf14 >=", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14LessThan(String value) {
            addCriterion("udf14 <", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14LessThanOrEqualTo(String value) {
            addCriterion("udf14 <=", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14Like(String value) {
            addCriterion("udf14 like", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotLike(String value) {
            addCriterion("udf14 not like", value, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14In(List<String> values) {
            addCriterion("udf14 in", values, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotIn(List<String> values) {
            addCriterion("udf14 not in", values, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14Between(String value1, String value2) {
            addCriterion("udf14 between", value1, value2, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf14NotBetween(String value1, String value2) {
            addCriterion("udf14 not between", value1, value2, "udf14");
            return (Criteria) this;
        }

        public Criteria andUdf15IsNull() {
            addCriterion("udf15 is null");
            return (Criteria) this;
        }

        public Criteria andUdf15IsNotNull() {
            addCriterion("udf15 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf15EqualTo(String value) {
            addCriterion("udf15 =", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotEqualTo(String value) {
            addCriterion("udf15 <>", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15GreaterThan(String value) {
            addCriterion("udf15 >", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15GreaterThanOrEqualTo(String value) {
            addCriterion("udf15 >=", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15LessThan(String value) {
            addCriterion("udf15 <", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15LessThanOrEqualTo(String value) {
            addCriterion("udf15 <=", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15Like(String value) {
            addCriterion("udf15 like", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotLike(String value) {
            addCriterion("udf15 not like", value, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15In(List<String> values) {
            addCriterion("udf15 in", values, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotIn(List<String> values) {
            addCriterion("udf15 not in", values, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15Between(String value1, String value2) {
            addCriterion("udf15 between", value1, value2, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf15NotBetween(String value1, String value2) {
            addCriterion("udf15 not between", value1, value2, "udf15");
            return (Criteria) this;
        }

        public Criteria andUdf16IsNull() {
            addCriterion("udf16 is null");
            return (Criteria) this;
        }

        public Criteria andUdf16IsNotNull() {
            addCriterion("udf16 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf16EqualTo(String value) {
            addCriterion("udf16 =", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotEqualTo(String value) {
            addCriterion("udf16 <>", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16GreaterThan(String value) {
            addCriterion("udf16 >", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16GreaterThanOrEqualTo(String value) {
            addCriterion("udf16 >=", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16LessThan(String value) {
            addCriterion("udf16 <", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16LessThanOrEqualTo(String value) {
            addCriterion("udf16 <=", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16Like(String value) {
            addCriterion("udf16 like", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotLike(String value) {
            addCriterion("udf16 not like", value, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16In(List<String> values) {
            addCriterion("udf16 in", values, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotIn(List<String> values) {
            addCriterion("udf16 not in", values, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16Between(String value1, String value2) {
            addCriterion("udf16 between", value1, value2, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf16NotBetween(String value1, String value2) {
            addCriterion("udf16 not between", value1, value2, "udf16");
            return (Criteria) this;
        }

        public Criteria andUdf17IsNull() {
            addCriterion("udf17 is null");
            return (Criteria) this;
        }

        public Criteria andUdf17IsNotNull() {
            addCriterion("udf17 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf17EqualTo(String value) {
            addCriterion("udf17 =", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotEqualTo(String value) {
            addCriterion("udf17 <>", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17GreaterThan(String value) {
            addCriterion("udf17 >", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17GreaterThanOrEqualTo(String value) {
            addCriterion("udf17 >=", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17LessThan(String value) {
            addCriterion("udf17 <", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17LessThanOrEqualTo(String value) {
            addCriterion("udf17 <=", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17Like(String value) {
            addCriterion("udf17 like", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotLike(String value) {
            addCriterion("udf17 not like", value, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17In(List<String> values) {
            addCriterion("udf17 in", values, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotIn(List<String> values) {
            addCriterion("udf17 not in", values, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17Between(String value1, String value2) {
            addCriterion("udf17 between", value1, value2, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf17NotBetween(String value1, String value2) {
            addCriterion("udf17 not between", value1, value2, "udf17");
            return (Criteria) this;
        }

        public Criteria andUdf18IsNull() {
            addCriterion("udf18 is null");
            return (Criteria) this;
        }

        public Criteria andUdf18IsNotNull() {
            addCriterion("udf18 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf18EqualTo(String value) {
            addCriterion("udf18 =", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotEqualTo(String value) {
            addCriterion("udf18 <>", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18GreaterThan(String value) {
            addCriterion("udf18 >", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18GreaterThanOrEqualTo(String value) {
            addCriterion("udf18 >=", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18LessThan(String value) {
            addCriterion("udf18 <", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18LessThanOrEqualTo(String value) {
            addCriterion("udf18 <=", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18Like(String value) {
            addCriterion("udf18 like", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotLike(String value) {
            addCriterion("udf18 not like", value, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18In(List<String> values) {
            addCriterion("udf18 in", values, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotIn(List<String> values) {
            addCriterion("udf18 not in", values, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18Between(String value1, String value2) {
            addCriterion("udf18 between", value1, value2, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf18NotBetween(String value1, String value2) {
            addCriterion("udf18 not between", value1, value2, "udf18");
            return (Criteria) this;
        }

        public Criteria andUdf19IsNull() {
            addCriterion("udf19 is null");
            return (Criteria) this;
        }

        public Criteria andUdf19IsNotNull() {
            addCriterion("udf19 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf19EqualTo(String value) {
            addCriterion("udf19 =", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotEqualTo(String value) {
            addCriterion("udf19 <>", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19GreaterThan(String value) {
            addCriterion("udf19 >", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19GreaterThanOrEqualTo(String value) {
            addCriterion("udf19 >=", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19LessThan(String value) {
            addCriterion("udf19 <", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19LessThanOrEqualTo(String value) {
            addCriterion("udf19 <=", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19Like(String value) {
            addCriterion("udf19 like", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotLike(String value) {
            addCriterion("udf19 not like", value, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19In(List<String> values) {
            addCriterion("udf19 in", values, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotIn(List<String> values) {
            addCriterion("udf19 not in", values, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19Between(String value1, String value2) {
            addCriterion("udf19 between", value1, value2, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf19NotBetween(String value1, String value2) {
            addCriterion("udf19 not between", value1, value2, "udf19");
            return (Criteria) this;
        }

        public Criteria andUdf20IsNull() {
            addCriterion("udf20 is null");
            return (Criteria) this;
        }

        public Criteria andUdf20IsNotNull() {
            addCriterion("udf20 is not null");
            return (Criteria) this;
        }

        public Criteria andUdf20EqualTo(String value) {
            addCriterion("udf20 =", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotEqualTo(String value) {
            addCriterion("udf20 <>", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20GreaterThan(String value) {
            addCriterion("udf20 >", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20GreaterThanOrEqualTo(String value) {
            addCriterion("udf20 >=", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20LessThan(String value) {
            addCriterion("udf20 <", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20LessThanOrEqualTo(String value) {
            addCriterion("udf20 <=", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20Like(String value) {
            addCriterion("udf20 like", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotLike(String value) {
            addCriterion("udf20 not like", value, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20In(List<String> values) {
            addCriterion("udf20 in", values, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotIn(List<String> values) {
            addCriterion("udf20 not in", values, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20Between(String value1, String value2) {
            addCriterion("udf20 between", value1, value2, "udf20");
            return (Criteria) this;
        }

        public Criteria andUdf20NotBetween(String value1, String value2) {
            addCriterion("udf20 not between", value1, value2, "udf20");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_uom
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 30 16:21:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_uom
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}