package cn.evun.coreframework.model;

import java.math.BigDecimal;
import java.util.Date;

public class Spu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.std_product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String stdProductNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.category_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.guidance_price
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private BigDecimal guidancePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.page_title
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String pageTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.distribution_condition
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String distributionCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.isvalidate
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Integer isvalidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.page_main_pic
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String pageMainPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.brand_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String editUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf1
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf2
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf3
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf4
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf5
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf6
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf7
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf8
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf9
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf10
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf11
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf12
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf13
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf14
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf15
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf16
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf17
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf18
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf19
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf20
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf21
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf22
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf23
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf24
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf25
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf26
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf27
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf28
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf29
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.cdf30
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String cdf30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.product_info
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    private String productInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.std_product_no
     *
     * @return the value of spu.std_product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getStdProductNo() {
        return stdProductNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.std_product_no
     *
     * @param stdProductNo the value for spu.std_product_no
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setStdProductNo(String stdProductNo) {
        this.stdProductNo = stdProductNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.category_id
     *
     * @return the value of spu.category_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.category_id
     *
     * @param categoryId the value for spu.category_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.guidance_price
     *
     * @return the value of spu.guidance_price
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public BigDecimal getGuidancePrice() {
        return guidancePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.guidance_price
     *
     * @param guidancePrice the value for spu.guidance_price
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setGuidancePrice(BigDecimal guidancePrice) {
        this.guidancePrice = guidancePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.page_title
     *
     * @return the value of spu.page_title
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getPageTitle() {
        return pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.page_title
     *
     * @param pageTitle the value for spu.page_title
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.distribution_condition
     *
     * @return the value of spu.distribution_condition
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getDistributionCondition() {
        return distributionCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.distribution_condition
     *
     * @param distributionCondition the value for spu.distribution_condition
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setDistributionCondition(String distributionCondition) {
        this.distributionCondition = distributionCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.isvalidate
     *
     * @return the value of spu.isvalidate
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Integer getIsvalidate() {
        return isvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.isvalidate
     *
     * @param isvalidate the value for spu.isvalidate
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setIsvalidate(Integer isvalidate) {
        this.isvalidate = isvalidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.page_main_pic
     *
     * @return the value of spu.page_main_pic
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getPageMainPic() {
        return pageMainPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.page_main_pic
     *
     * @param pageMainPic the value for spu.page_main_pic
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setPageMainPic(String pageMainPic) {
        this.pageMainPic = pageMainPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.brand_id
     *
     * @return the value of spu.brand_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.brand_id
     *
     * @param brandId the value for spu.brand_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.create_user_id
     *
     * @return the value of spu.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.create_user_id
     *
     * @param createUserId the value for spu.create_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.create_time
     *
     * @return the value of spu.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.create_time
     *
     * @param createTime the value for spu.create_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.edit_user_id
     *
     * @return the value of spu.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getEditUserId() {
        return editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.edit_user_id
     *
     * @param editUserId the value for spu.edit_user_id
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setEditUserId(String editUserId) {
        this.editUserId = editUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.edit_time
     *
     * @return the value of spu.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.edit_time
     *
     * @param editTime the value for spu.edit_time
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf1
     *
     * @return the value of spu.cdf1
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf1() {
        return cdf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf1
     *
     * @param cdf1 the value for spu.cdf1
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf1(String cdf1) {
        this.cdf1 = cdf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf2
     *
     * @return the value of spu.cdf2
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf2() {
        return cdf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf2
     *
     * @param cdf2 the value for spu.cdf2
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf2(String cdf2) {
        this.cdf2 = cdf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf3
     *
     * @return the value of spu.cdf3
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf3() {
        return cdf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf3
     *
     * @param cdf3 the value for spu.cdf3
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf3(String cdf3) {
        this.cdf3 = cdf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf4
     *
     * @return the value of spu.cdf4
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf4() {
        return cdf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf4
     *
     * @param cdf4 the value for spu.cdf4
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf4(String cdf4) {
        this.cdf4 = cdf4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf5
     *
     * @return the value of spu.cdf5
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf5() {
        return cdf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf5
     *
     * @param cdf5 the value for spu.cdf5
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf5(String cdf5) {
        this.cdf5 = cdf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf6
     *
     * @return the value of spu.cdf6
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf6() {
        return cdf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf6
     *
     * @param cdf6 the value for spu.cdf6
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf6(String cdf6) {
        this.cdf6 = cdf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf7
     *
     * @return the value of spu.cdf7
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf7() {
        return cdf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf7
     *
     * @param cdf7 the value for spu.cdf7
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf7(String cdf7) {
        this.cdf7 = cdf7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf8
     *
     * @return the value of spu.cdf8
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf8() {
        return cdf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf8
     *
     * @param cdf8 the value for spu.cdf8
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf8(String cdf8) {
        this.cdf8 = cdf8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf9
     *
     * @return the value of spu.cdf9
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf9() {
        return cdf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf9
     *
     * @param cdf9 the value for spu.cdf9
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf9(String cdf9) {
        this.cdf9 = cdf9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf10
     *
     * @return the value of spu.cdf10
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf10() {
        return cdf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf10
     *
     * @param cdf10 the value for spu.cdf10
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf10(String cdf10) {
        this.cdf10 = cdf10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf11
     *
     * @return the value of spu.cdf11
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf11() {
        return cdf11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf11
     *
     * @param cdf11 the value for spu.cdf11
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf11(String cdf11) {
        this.cdf11 = cdf11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf12
     *
     * @return the value of spu.cdf12
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf12() {
        return cdf12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf12
     *
     * @param cdf12 the value for spu.cdf12
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf12(String cdf12) {
        this.cdf12 = cdf12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf13
     *
     * @return the value of spu.cdf13
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf13() {
        return cdf13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf13
     *
     * @param cdf13 the value for spu.cdf13
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf13(String cdf13) {
        this.cdf13 = cdf13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf14
     *
     * @return the value of spu.cdf14
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf14() {
        return cdf14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf14
     *
     * @param cdf14 the value for spu.cdf14
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf14(String cdf14) {
        this.cdf14 = cdf14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf15
     *
     * @return the value of spu.cdf15
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf15() {
        return cdf15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf15
     *
     * @param cdf15 the value for spu.cdf15
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf15(String cdf15) {
        this.cdf15 = cdf15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf16
     *
     * @return the value of spu.cdf16
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf16() {
        return cdf16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf16
     *
     * @param cdf16 the value for spu.cdf16
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf16(String cdf16) {
        this.cdf16 = cdf16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf17
     *
     * @return the value of spu.cdf17
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf17() {
        return cdf17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf17
     *
     * @param cdf17 the value for spu.cdf17
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf17(String cdf17) {
        this.cdf17 = cdf17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf18
     *
     * @return the value of spu.cdf18
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf18() {
        return cdf18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf18
     *
     * @param cdf18 the value for spu.cdf18
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf18(String cdf18) {
        this.cdf18 = cdf18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf19
     *
     * @return the value of spu.cdf19
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf19() {
        return cdf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf19
     *
     * @param cdf19 the value for spu.cdf19
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf19(String cdf19) {
        this.cdf19 = cdf19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf20
     *
     * @return the value of spu.cdf20
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf20() {
        return cdf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf20
     *
     * @param cdf20 the value for spu.cdf20
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf20(String cdf20) {
        this.cdf20 = cdf20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf21
     *
     * @return the value of spu.cdf21
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf21() {
        return cdf21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf21
     *
     * @param cdf21 the value for spu.cdf21
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf21(String cdf21) {
        this.cdf21 = cdf21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf22
     *
     * @return the value of spu.cdf22
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf22() {
        return cdf22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf22
     *
     * @param cdf22 the value for spu.cdf22
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf22(String cdf22) {
        this.cdf22 = cdf22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf23
     *
     * @return the value of spu.cdf23
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf23() {
        return cdf23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf23
     *
     * @param cdf23 the value for spu.cdf23
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf23(String cdf23) {
        this.cdf23 = cdf23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf24
     *
     * @return the value of spu.cdf24
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf24() {
        return cdf24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf24
     *
     * @param cdf24 the value for spu.cdf24
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf24(String cdf24) {
        this.cdf24 = cdf24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf25
     *
     * @return the value of spu.cdf25
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf25() {
        return cdf25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf25
     *
     * @param cdf25 the value for spu.cdf25
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf25(String cdf25) {
        this.cdf25 = cdf25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf26
     *
     * @return the value of spu.cdf26
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf26() {
        return cdf26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf26
     *
     * @param cdf26 the value for spu.cdf26
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf26(String cdf26) {
        this.cdf26 = cdf26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf27
     *
     * @return the value of spu.cdf27
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf27() {
        return cdf27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf27
     *
     * @param cdf27 the value for spu.cdf27
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf27(String cdf27) {
        this.cdf27 = cdf27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf28
     *
     * @return the value of spu.cdf28
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf28() {
        return cdf28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf28
     *
     * @param cdf28 the value for spu.cdf28
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf28(String cdf28) {
        this.cdf28 = cdf28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf29
     *
     * @return the value of spu.cdf29
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf29() {
        return cdf29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf29
     *
     * @param cdf29 the value for spu.cdf29
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf29(String cdf29) {
        this.cdf29 = cdf29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.cdf30
     *
     * @return the value of spu.cdf30
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getCdf30() {
        return cdf30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.cdf30
     *
     * @param cdf30 the value for spu.cdf30
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setCdf30(String cdf30) {
        this.cdf30 = cdf30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.product_info
     *
     * @return the value of spu.product_info
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public String getProductInfo() {
        return productInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.product_info
     *
     * @param productInfo the value for spu.product_info
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    public void setProductInfo(String productInfo) {
        this.productInfo = productInfo;
    }
}