ALTER TABLE `spu`
  CHANGE COLUMN `category_id` `category_id` INT NULL DEFAULT NULL COMMENT '业务分类编码' ,
  CHANGE COLUMN `page_main_pic` `page_main_pic` TEXT NULL DEFAULT NULL COMMENT '页面主图' ,
  ADD COLUMN `lv1_category_id` INT(11) NULL DEFAULT NULL COMMENT '底层一级分类' AFTER `std_product_no`,
  ADD COLUMN `lv1_category_no` VARCHAR(255) NULL DEFAULT NULL COMMENT '底层一级分类编码' AFTER `lv1_category_id`,
  ADD COLUMN `lv2_category_id` INT(11) NULL DEFAULT NULL COMMENT '底层二级分类' AFTER `lv1_category_no`,
  ADD COLUMN `lv2_category_no` VARCHAR(255) NULL DEFAULT NULL COMMENT '底层二级分类编码' AFTER `lv2_category_id`,
  ADD COLUMN `category_no` VARCHAR(256) NULL DEFAULT NULL COMMENT '细分类编码' AFTER `category_id`,
  ADD COLUMN `lv1_category_sp_id` INT(11) NULL DEFAULT NULL COMMENT '业务一级分类' AFTER `category_no`,
  ADD COLUMN `lv1_category_sp_no` VARCHAR(255) NULL DEFAULT NULL COMMENT '业务一级分类编码' AFTER `lv1_category_sp_id`,
  ADD COLUMN `lv2_category_sp_id` INT(11) NULL DEFAULT NULL COMMENT '业务二级分类' AFTER `lv1_category_sp_no`,
  ADD COLUMN `lv2_category_sp_no` VARCHAR(255) NULL DEFAULT NULL COMMENT '业务二级分类编码' AFTER `lv2_category_sp_id`,
  ADD COLUMN `category_sp_id` INT(11) NULL DEFAULT NULL COMMENT '业务三级分类' AFTER `lv2_category_sp_no`,
  ADD COLUMN `category_sp_no` VARCHAR(256) NULL DEFAULT NULL COMMENT '业务三级分类编码' AFTER `category_sp_id`,
  ADD COLUMN `mnemonic_code` VARCHAR(45) NULL AFTER `category_sp_no`,
  ADD COLUMN `rule_size` VARCHAR(45) NULL AFTER `cdf30`,
  ADD COLUMN `min_unit` VARCHAR(45) NULL AFTER `rule_size`,
  ADD COLUMN `weight` DOUBLE NULL COMMENT '重量(kg)' AFTER `min_unit`,
  ADD COLUMN `height` DOUBLE NULL COMMENT '高度(cm)' AFTER `weight`,
  ADD COLUMN `width` DOUBLE NULL COMMENT '宽度(cm)' AFTER `height`,
  ADD COLUMN `length` DOUBLE NULL COMMENT '长度(cm)' AFTER `width`,
  ADD COLUMN `shelf_time` DATETIME NULL COMMENT '上架时间' AFTER `length`;
