package cn.evun.coreframework.dao;

import cn.evun.coreframework.model.InvUnit;
import cn.evun.coreframework.model.InvUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int countByExample(InvUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int deleteByExample(InvUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int insert(InvUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int insertSelective(InvUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    List<InvUnit> selectByExample(InvUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    InvUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") InvUnit record, @Param("example") InvUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByExample(@Param("record") InvUnit record, @Param("example") InvUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByPrimaryKeySelective(InvUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inv_unit
     *
     * @mbggenerated Thu Aug 30 16:21:57 CST 2018
     */
    int updateByPrimaryKey(InvUnit record);
}