package cn.evun.coreframework.dao;

import cn.evun.coreframework.model.SkuUpc;
import cn.evun.coreframework.model.SkuUpcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkuUpcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int countByExample(SkuUpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int deleteByExample(SkuUpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int insert(SkuUpc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int insertSelective(SkuUpc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    List<SkuUpc> selectByExample(SkuUpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    SkuUpc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") SkuUpc record, @Param("example") SkuUpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int updateByExample(@Param("record") SkuUpc record, @Param("example") SkuUpcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int updateByPrimaryKeySelective(SkuUpc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_upc
     *
     * @mbggenerated Wed Aug 29 15:22:26 CST 2018
     */
    int updateByPrimaryKey(SkuUpc record);
}